#!/usr/bin/env python
# coding: utf-8

# # AIGC sentiment affiliation
# This expirement is for checking the emotional bias of the content generated by AI

import pandas as pd
import ollama
from tqdm import tqdm

# load dataset of weibo text[no spcific topic]
df = pd.read_csv("data/fulldata_forembedding[Reddit][withorginal].csv")
df.info()


# Calling ollama
all_responses = []
batch_size = 100  # Define the size of each batch saved

for idx, row in tqdm(df.iterrows(), total=df.shape[0], desc="Caculate embedding"):
    try:
        user_text = row['text']
        response = ollama.embeddings(model='llama3:70b-instruct', prompt=user_text)
        all_responses.append(response)
        
    
        if (idx + 1) % batch_size == 0:
            df.loc[idx - batch_size + 1:idx, 'response llama embed'] = all_responses[-batch_size:]
            df.to_csv(
                f"data_Twitter/Twitter_fulldata_forembedding[llama response].csv",
                index=False
            )
            all_responses = []  
            
    except Exception as e:
        print(f"Error at index {idx}: {e}")
        continue  

# save the left responses
if all_responses:
    df.loc[len(df) - len(all_responses):, 'response llama embed'] = all_responses
    df.to_csv(
        f"data_Twitter/Twitter_fulldata_forembedding[llama response].csv",
        index=False
    )


